# Opciones de patrocinio para YT Data Extractor

# Enlaces a plataformas de financiación
github: carlosrodera
patreon: # Agregar usuario de Patreon si existe
open_collective: # Agregar nombre de Open Collective si existe
ko_fi: # Agregar nombre de Ko-fi si existe
tidelift: # Agregar identificador de paquete Tidelift
community_bridge: # Agregar nombre de proyecto Community Bridge
liberapay: # Agregar nombre de Liberapay
issuehunt: # Agregar nombre de IssueHunt
otechie: # Agregar nombre de Otechie
custom: ['https://carlosrodera.com/donar']
