name: MCP Repository Setup

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup MCP
        uses: microsoft/mcp-action@v1
        with:
          repository: YT-Data-Extractor
          visibility: public
          description: "Extensión para extraer datos de YouTube"
          topics: youtube,data-extraction,chrome-extension
          license: MIT
          readme: |
            # YT Data Extractor

            Una extensión de Chrome para extraer datos de YouTube de manera eficiente.

            ## Características

            - Extracción de datos de videos de YouTube
            - Interfaz intuitiva
            - Exportación de datos en múltiples formatos

            ## Instalación

            1. Clona este repositorio
            2. Abre Chrome y ve a `chrome://extensions/`
            3. Activa el "Modo desarrollador"
            4. Haz clic en "Cargar descomprimida" y selecciona la carpeta de la extensión

            ## Uso

            1. Navega a cualquier video de YouTube
            2. Haz clic en el icono de la extensión
            3. Los datos se extraerán automáticamente

            ## Licencia

            MIT License 